# Copyright 2026 Matheus Pimenta.
# SPDX-License-Identifier: AGPL-3.0

rbac:
  serviceAccountName: "" # When set, skip creating ServiceAccount, ClusterRole and ClusterRoleBinding.

image:
  repository: ghcr.io/matheuscscp/cloudflare-gateway-controller
  tag: "" # Defaults to .Chart.AppVersion.
  pullPolicy: IfNotPresent

replicas: 1

config:
  clusterName: "" # Required. Unique cluster identifier for deterministic Cloudflare resource naming.
  cloudflared:
    image:
      repository: "" # Defaults to the built-in DefaultCloudflaredImage repository.
      tag: "" # Defaults to the built-in DefaultCloudflaredImage tag.
  sidecar:
    enabled: true
    image:
      repository: "" # Defaults to .Values.image.repository.
      tag: "" # Defaults to .Values.image.tag.

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL

podAnnotations: {}
podArgs: []
podEnv: []
podVolumes: []
podVolumeMounts: []
