#!/usr/bin/env bash
# Copyright 2026 Matheus Pimenta.
# SPDX-License-Identifier: AGPL-3.0
#
# Generates the Helm chart ClusterRole template from the controller-gen
# output at config/rbac/role.yaml.  Run via "make manifests".

set -euo pipefail

GENERATED_RBAC=config/rbac/role.yaml
CHART_CLUSTERROLE=charts/cloudflare-gateway-controller/templates/clusterrole.yaml

# Extract rules block from generated ClusterRole.
RULES=$(sed -n '/^rules:/,$p' "$GENERATED_RBAC")

# Single-quoted heredoc delimiter prevents shell expansion of {{ }}.
cat > "$CHART_CLUSTERROLE" <<'HEADER'
# Generated by controller-gen from kubebuilder RBAC markers. DO NOT EDIT.
# To update, run: make manifests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    app.kubernetes.io/name: cloudflare-gateway-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
HEADER

echo "$RULES" >> "$CHART_CLUSTERROLE"
